### ISSUE TITLE
High CPU usage and delay for highly compressed gz files

### ISSUE THREAD

**Issue by vikstrous** [secretsquirrel/BDFProxy#10]
My pull request https://github.com/secretsquirrel/BDFProxy/pull/6 took care of not using a ton of disk space when processing highly compressed gz files, but it still uses a lot of CPU. This problem is really non-trivial and the python tarfile library limits our options a bit.

There are two problems:
1. Tar files don't have a global header so we don't know if there are more files until we get to them
   
   1.1. gz is stream oriented and doesn't allow seeking
2. We have 3 possible ways to modify the tar file:
   
   2.1. Remove the relevant file and then add a new version - we can't do this because the library doesn't let us
   
   2.2. Create a new archive and add all the old files into the new archive - we can do this but it's slow because we have to decompress and compress again
   
   2.3. Append the new backdoored files to the end of the old archive, "overriding" the old ones - this works but always produces a bigger archive and retains both versions of the files

**Comment by secretsquirrel** [comment]
https://github.com/secretsquirrel/BDFProxy#bdfproxy-is-no-longer-maintained-or-supported
