### ISSUE TITLE
Transparent Mode Failure [Errno 92]

### ISSUE THREAD

**Issue by lxj616** [secretsquirrel/BDFProxy#23]
Tested on Kali 1.1.0a and Kali 1.0.9 , On both git newest version / (apt-get install) version
Using iptables redirect 80 port http traffic to 8080(.cfg set so , set to transparent already)
Browser indicates  Transparent Mode Failure [Errno 92] (On all browsers)
msfconsole seems to be working fine , testing iptables traffic redirection with burpsuite seems fine, no error report from bdf_proxy.py
And I tested "None", certainly it won't work with iptables...
Help plz

**Comment by secretsquirrel** [comment]
Wait. You are using it with burp?

**Comment by lxj616** [comment]
No , I use burp to test my iptables redirection , Not using it with bdfproxy

**Comment by secretsquirrel** [comment]
Hmm. I can't/won't help you with your iptables setup. Though, have a look at this: https://github.com/offensive-security/kali-nethunter/blob/f43f33f12da76e63054baf1991d2bb9e312810e1/utils/manna/start-nat-simple-bdf-lollipop.sh
