### ISSUE TITLE
Support of mitmproxy >= 0.13

### ISSUE THREAD

**Issue by rhertzog** [secretsquirrel/BDFProxy#27]
Hello,

I saw that you added documentation saying that BDFProxy only works with mitmproxy >= 0.11 and < 0.13. But mitmproxy 0.13 is the current version and it's not very nice to require a version older than the current one...

At least in Kali we already have mitmproxy 0.13 together with BDFProxy 0.3.2. We were about to upload 0.3.5 when we saw this restriction.

Can you say a bit more why you put this restriction into place?

**Comment by secretsquirrel** [comment]
I haven't tested it on mitmproxy .13 yet. Whenever mitmproxy updates their major version number, they usually make subtle changes to their libmproxy API, which BDFProxy uses directly.

If you say it works perfectly with .13 then that's great.

**Comment by rhertzog** [comment]
On Wed, 02 Sep 2015, secret squirrel wrote:
> If you say it works perfectly with .13 then that's great.

I'm just a packager so I don't know but at least it released that way in
Kali 2 and we did not get any complaint so far. So that points in this
direction :-)

Cheers,
-- 
Raphaël Hertzog ◈ Debian Developer

Support Debian LTS: http://www.freexian.com/services/debian-lts.html
Learn to master Debian: http://debian-handbook.info/get/

**Comment by dirkjanm** [comment]
FWIW, for me the latest version is working fine in Kali 2 with mitmproxy 0.13

**Comment by secretsquirrel** [comment]
K. Thanks. I'll update the readme.

**Comment by secretsquirrel** [comment]
Updated: https://github.com/secretsquirrel/BDFProxy/commit/f2b1a3e7bc455bfaeb0f8b0dfed0935f06c1cc5c
