### ISSUE TITLE
Default config for WindowsIntelx86 uses wrong combination of payload/shell

### ISSUE THREAD

**Issue by dirkjanm** [secretsquirrel/BDFProxy#28]
I was having trouble with the default configuration because no shell would open with patched binaries, but it turns out that the default is to patch with a simple shell while the payload uses meterpreter.
While not a bug per se, it might make more sense to have the default config be consistent by changing
`MSFPAYLOAD = windows/meterpreter/reverse_tcp`
to
`MSFPAYLOAD = windows/shell/reverse_tcp`
in the WindowsIntelx86 section of the default config.

**Comment by secretsquirrel** [comment]
Cool.

Updated the payload to match MSFPAYLOAD. 

https://github.com/secretsquirrel/BDFProxy/commit/9c9994e121dcdff1b56396c906d38cb05d04dc70
