### ISSUE TITLE
Feature: Streaming mode

### ISSUE THREAD

**Issue by vikstrous** [secretsquirrel/BDFProxy#3]
It would be really cool if this could patch large executable files while they are being downloaded. I know this is doable for ELF files. Is it possible for PE? The advantage of this would be that it won't slow down the download and it will be practically undetectable. Unfortunately, downloading an uncompressed, untar'd ELF file is not a common use case, so this would also require support for streaming decompression and compression of tar.gz, zip and other formats.

**Comment by secretsquirrel** [comment]
https://github.com/secretsquirrel/BDFProxy#bdfproxy-is-no-longer-maintained-or-supported
