### ISSUE TITLE
BDFproxy Crashed v0.3.6 kali

### ISSUE THREAD

**Issue by justuandme** [secretsquirrel/BDFProxy#31]
Hi,

i just download the new version of BDFproxy and tested it.... as soon as i started it it gets crashed after 3 4 seconds...here is the crash log.

root@kali:~/BDFProxy# ./bdf_proxy.py
[!] Writing resource script.
[!] Resource writen to bdfproxy_msf_resource.rc
[!] Configuring traffic forwarding
[] Starting BDFProxy
[] Version: v0.3.6
[*] Author: @midnite_runr | the[.]midnite).(runrgmail|.|com

********** REQUEST **********
[] HOST: xx.xx.xx.xxx
[] PATH: /v3/links/view
********** END REQUEST **********
========== RESPONSE ==========
[] HOST: xx.xx.xx.xx
[] PATH: /v3/links/view
Traceback (most recent call last):
File "./bdf_proxy.py", line 841, in
m.run()
File "./bdf_proxy.py", line 177, in run
return controller.Master.run(self)
File "/usr/lib/python2.7/dist-packages/libmproxy/controller.py", line 111, in run
self.tick(self.masterq, 0.01)
File "/usr/lib/python2.7/dist-packages/libmproxy/controller.py", line 101, in tick
self.handle(*msg)
File "/usr/lib/python2.7/dist-packages/libmproxy/controller.py", line 118, in handle
m(obj)
File "./bdf_proxy.py", line 727, in handle_response
mime_type = magic.from_buffer(flow.reply.obj.response.content, mime=True)
AttributeError: 'module' object has no attribute 'from_buffer'

im using kali GNU/Linux 1.1.0
the BDFproxy old version which i downloaded from kali repo apt-get install bdfproxy works fine.
but this new one is not working... is their is any module im missing here .. then plz tell me which one to install?

**Comment by justuandme** [comment]
ohh i found solution, i shoudn't be so hurry in making issue here... i just read that the libmagic is not installed.
so i installed it with pip install python-magic and now it works fine.

**Comment by secretsquirrel** [comment]
Good stuff.
