### ISSUE TITLE
ImportError: No module named libmproxy

### ISSUE THREAD

**Issue by FreelancePentester** [secretsquirrel/BDFProxy#36]
Traceback (most recent call last):
  File "./bdf_proxy.py", line 31, in <module>
    from libmproxy import controller, proxy, platform
ImportError: No module named libmproxy

**Comment by secretsquirrel** [comment]
Because MITMPROXY moved libmproxy to mitmproxy (library naming), we'll be stuck at v.0.16 until everything is updated.
Get it here: https://github.com/mitmproxy/mitmproxy/tree/v0.16

**Comment by secretsquirrel** [comment]
If you want to fix that issue feel free. :) Pull requests welcome.
