### ISSUE TITLE
BDFProxy: No module named libmproxy:

### ISSUE THREAD

**Issue by manish199014** [secretsquirrel/BDFProxy#37]
Hello 

**I am using a Linux 4.5.0-kali1-686-pae #1 SMP Debian 4.5.5-1kali1 (2016-06-06) i686 GNU/Linux**

Traceback (most recent call last):
  File "./bdf_proxy.py", line 31, in <module>
    from libmproxy import controller, proxy, platform
ImportError: No module named libmproxy

I am trying to run BDFProxy but everytime I am getting an above error. I have also tried to run install.sh and update.sh. 

For Install.sh

root@Jhonny:/usr/share/bdfproxy# ./install.sh
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Requirement already satisfied (use --upgrade to upgrade): configobj in /usr/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from configobj)
Updating BDFProxy
fatal: Not a git repository (or any of the parent directories): .git
Updating BDF
fatal: Not a git repository (or any of the parent directories): .git
./update.sh: line 7: ./install.sh: No such file or directory

For Update.sh

root@Jhonny:/usr/share/bdfproxy# ./update.sh
Updating BDFProxy
fatal: Not a git repository (or any of the parent directories): .git
Updating BDF
fatal: Not a git repository (or any of the parent directories): .git
./update.sh: line 7: ./install.sh: No such file or directory

Looking forward to get your response as soon as possible. 
Best Regards
MR

**Comment by secretsquirrel** [comment]
Did you try installing bdfproxy from the Kali repo?


apt-get install bdfproxy

On Sat, Jun 18, 2016 at 12:12 PM, manish199014 <notifications@github.com>
wrote:

> Hello
>
> *I am using a Linux 4.5.0-kali1-686-pae #1
> <https://github.com/secretsquirrel/BDFProxy/issues/1> SMP Debian
> 4.5.5-1kali1 (2016-06-06) i686 GNU/Linux*
>
> Traceback (most recent call last):
> File "./bdf_proxy.py", line 31, in
> from libmproxy import controller, proxy, platform
> ImportError: No module named libmproxy
>
> I am trying to run BDFProxy but everytime I am getting an above error. I
> have also tried to run install.sh and update.sh.
>
> For Install.sh
>
> root@Jhonny:/usr/share/bdfproxy# ./install.sh
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> Requirement already satisfied (use --upgrade to upgrade): configobj in
> /usr/lib/python2.7/dist-packages
> Requirement already satisfied (use --upgrade to upgrade): six in
> /usr/lib/python2.7/dist-packages (from configobj)
> Updating BDFProxy
> fatal: Not a git repository (or any of the parent directories): .git
> Updating BDF
> fatal: Not a git repository (or any of the parent directories): .git
> ./update.sh: line 7: ./install.sh: No such file or directory
>
> For Update.sh
>
> root@Jhonny:/usr/share/bdfproxy# ./update.sh
> Updating BDFProxy
> fatal: Not a git repository (or any of the parent directories): .git
> Updating BDF
> fatal: Not a git repository (or any of the parent directories): .git
> ./update.sh: line 7: ./install.sh: No such file or directory
>
> Looking forward to get your response as soon as possible.
> Best Regards
> MR
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/secretsquirrel/BDFProxy/issues/37>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABmh6pDuewwTzct1jIYIMpaXy-A7hA41ks5qNBj7gaJpZM4I4-mO>
> .
>



-- 
Josh
703.507.4468

**Comment by secretsquirrel** [comment]
Seems Kali has updated to the most updated version of mitmproxy.  You'll need to downgrade mitmproxy to v0.16 until I can update BDFProxy.

https://github.com/secretsquirrel/BDFProxy#now-only-works-with-v016--mitmproxy--v011

**Comment by manish199014** [comment]
Hi , 

Yes I try from the repositryies on github and apt-get
