### ISSUE TITLE
Update BDFProxy to Support v0.17+ MitmProxy

### ISSUE THREAD

**Issue by secretsquirrel** [secretsquirrel/BDFProxy#38]
Libmproxy is no more.

**Comment by manish199014** [comment]
Hello, 

I have updated the BDFproxy but still not working. Could you please let us know from where we can download the latest support v0.17+MitmProxy

**Comment by FreelancePentester** [comment]
hope that new bdfproxy version will be coming soon as possible.

**Comment by secretsquirrel** [comment]
This week has been busy, however I have released docker images that 'just work'.

Docker:

sudo echo 1 > /proc/sys/net/ipv4/ip_forward # linux 
 sudo sysctl -w net.inet.ip.forwarding=1 # macOS 
 docker pull secretsquirrel/bdfproxy 
 docker run -it -p 8080:8080 secretsquirrel/bdfproxy bash 
# ./bdf_proxy.py

**Comment by FreelancePentester** [comment]
great work. But i am waiting for new version. Because, on Kali NetHunter, i can not come back to mitmproxy 0.16. :) If possible, it is a wonderful to see bdfproxy can patch backdoor apk file. :D.

**Comment by secretsquirrel** [comment]
I see. Ok. Yeah.. Apk would be cool. I think have an open issue on that.

**Comment by FreelancePentester** [comment]
I wrote bash script for automatically backdoor file, but I am newbie on Python, so I can not write it. Hope that you can do it. 😃

**Comment by secretsquirrel** [comment]
Complete. git pull && ./update.sh

**Comment by secretsquirrel** [comment]
Issue to update Kali submitted: https://bugs.kali.org/view.php?id=3391
