### ISSUE TITLE
onionduke problem

### ISSUE THREAD

**Issue by andrew98450** [secretsquirrel/BDFProxy#43]
this my setting
![9](https://cloud.githubusercontent.com/assets/16256818/17721803/9963f7fa-645f-11e6-8c5e-cc00fe3afdce.JPG)
but....
![6](https://cloud.githubusercontent.com/assets/16256818/17721808/a128006c-645f-11e6-9706-a4f0abc2abff.JPG)

**Comment by joshpitts-okta** [comment]
I think you are missing aPLib appack install.
To test, run
```
$ appack
```

If you have an error it is not installed.  

To install it see:
https://github.com/secretsquirrel/BDFProxy#install
OR
Docker install: https://github.com/secretsquirrel/BDFProxy#now-only-works-with-v017--mitmproxy--v011

**Comment by joshpitts-okta** [comment]
Works fine for me:

![http://i.imgur.com/fYsBtKk.png](http://i.imgur.com/fYsBtKk.png)

**Comment by secretsquirrel** [comment]
I think you are missing aPLib appack install.
To test, run
```
$ appack
```

If you have an error it is not installed.  

To install it see:
https://github.com/secretsquirrel/BDFProxy#install
OR
Docker install: https://github.com/secretsquirrel/BDFProxy#now-only-works-with-v017--mitmproxy--v011

**Comment by secretsquirrel** [comment]
Works fine for me:

![http://i.imgur.com/fYsBtKk.png](http://i.imgur.com/fYsBtKk.png)

**Comment by andrew98450** [comment]
make error....
![95](https://cloud.githubusercontent.com/assets/16256818/17722933/9107c7ea-6468-11e6-92c3-13b21c5354ef.JPG)

**Comment by andrew98450** [comment]
is ok thank!!
![98](https://cloud.githubusercontent.com/assets/16256818/17723471/f68154de-646c-11e6-8b8b-930ccbd5c3ba.JPG)
