### ISSUE TITLE
follow fhs structure, aka make it distro friendly

### ISSUE THREAD

**Issue by blshkv** [secretsquirrel/BDFProxy#44]
Hi, I'm trying to port the tool to pentoo and facing various difficulties.

You seems expect a user to run the tool from a random folder as root. The tool creates several files including log and .rc in that folder. Unfortunately, this is a bad behaviour if the tool has been installed into a system folder.

You should install .cfg file into /etc, the-backdoor-factory should be a python module installed into site-packages folder, all output should go to ~/.bdfproxy folder or similar.

I tried to symlink the bdf folder, adjust paths in the config file but it's all hacks.
Please consider.

FYI: http://www.pathname.com/fhs/pub/fhs-2.3.html
https://github.com/pentoo/pentoo-overlay/issues/115

**Comment by secretsquirrel** [comment]
I wasn't expecting distros to pick this up when I first created it, but I won't complain. I know Kali and nethunter made it work, I haven't looked at how specifically. I'm sure it's a symlink shuffle. 

This has been on my internal to do for some time... that and install via pip.  BDF is going through a major revamp and should be done in summer 2017 (including this).

**Comment by secretsquirrel** [comment]
https://github.com/secretsquirrel/BDFProxy#bdfproxy-is-no-longer-maintained-or-supported
