### ISSUE TITLE
bdfproxy unexpected keyword argument 'body_size_limit'

### ISSUE THREAD

**Issue by reapersaint** [secretsquirrel/BDFProxy#46]
BDFProxy v0.3.9-0kali
mitmproxy 0.18.2-0kali
File "./bdf_proxy.py", line 824, in <module>
    mode=user_config['Overall']['proxyMode'],
TypeError: **init**() got an unexpected keyword argument 'body_size_limit'

Any ideas?

**Comment by secretsquirrel** [comment]
Yep: https://github.com/secretsquirrel/BDFProxy/blob/master/README.md#now-only-works-with-v017--mitmproxy--v011
