### ISSUE TITLE
can't get the request of pe file

### ISSUE THREAD

**Issue by icepng** [secretsquirrel/BDFProxy#47]
I can get the request about "html", "css", "zip" etc. in function handle_request, but I can't get the request about ".exe", is the error of my mitmproxy? thx.

**Comment by secretsquirrel** [comment]
I can't determine what your issue is by this vague report.  I need to be able to recreate the issue.
Look at this issue report and try to provide the same information: https://github.com/secretsquirrel/BDFProxy/issues/39

**Comment by icepng** [comment]
no that issue, he got the request and try to patch in response, however, i can't get the request about a ‘.exe’ file.

**Comment by secretsquirrel** [comment]
bdf_proxy.py output, proxy.log output, and config on pastebin please.

**Comment by secretsquirrel** [comment]
Just no.
