### ISSUE TITLE
AttributeError: 'ProxyMaster' object has no attribute 'log'

### ISSUE THREAD

**Issue by 0MazaHacka0** [secretsquirrel/BDFProxy#48]
[!] Writing resource script.
[!] Resource writen to bdfproxy_msf.rc
[!] Configuring traffic forwarding
[*] Starting BDFProxy
[*] Version: v0.3.8
[*] Author: @midnite_runr | the[.]midnite).(runr<at>gmail|.|com
Traceback (most recent call last):
  File "./bdf_proxy.py", line 883, in <module>
    m.run()
  File "./bdf_proxy.py", line 176, in run
    return controller.Master.run(self)
  File "/usr/lib/python2.7/dist-packages/mitmproxy/controller.py", line 142, in run
    self.tick(0.1)
  File "/usr/lib/python2.7/dist-packages/mitmproxy/controller.py", line 154, in tick
    handle_func = getattr(self, mtype)
AttributeError: 'ProxyMaster' object has no attribute 'log'

What did i do wrong?

**Comment by secretsquirrel** [comment]
Please do the following:
```
mitmproxy --version
```

What do you get?

**Comment by 0MazaHacka0** [comment]
@secretsquirrel mitmproxy 0.18.2

**Comment by secretsquirrel** [comment]
BDFProxy only supports mitmproxy v011 => v017

https://github.com/secretsquirrel/BDFProxy#now-only-works-with-v017--mitmproxy--v011

pip install mitmproxy==0.17

**Comment by 0MazaHacka0** [comment]
Ha, i installed mitmproxy 0.14 and now i get 
Traceback (most recent call last):
  File "./bdf_proxy.py", line 821, in <module>
    config = proxy.ProxyConfig(options.Options(clientcerts=os.path.expanduser(user_config['Overall']['certLocation']),
NameError: name 'options' is not defined
